using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameStart : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        GameObject originalPlayer = GameObject.Find("man-cowboy_Rig");
        Vector3 opp = originalPlayer.transform.position;

        for(int i=0;i<10;i++)
        {
            GameObject player = Instantiate(originalPlayer);
            player.transform.position = player.transform.position + new Vector3((i+1) * 0.1f, 0, 0 );
        }


    }

   
}
